listener 8883
protocol mqtt
max_connections 1000

cafile /mosquitto/certs/client-ca.crt
certfile /mosquitto/certs/server/fullchain.pem
keyfile /mosquitto/certs/server/privkey.pem
tls_version tlsv1.2
require_certificate true
use_identity_as_username true

allow_anonymous false
acl_file /mosquitto/config/acl

max_packet_size 262144
max_queued_messages 1000
max_queued_bytes 10485760

persistence true
persistence_location /mosquitto/data/
autosave_interval 30

log_dest stdout
log_type all
connection_messages true
